### PR TITLE
default schemaPath in visit anyOf or oneOf

### PR DESCRIPTION
**Pull request by shalevshalit**

### CODE REVIEW

**Comment by mAiNiNfEcTiOn** [comment]
@shalevshalit can you add a unit test to prevent this from happening in the future, then?

**Comment by LinusU** [comment]
Would **love** a unit test from anyone as a PR 👍

**Comment by LinusU** [comment]
Thank you for the quick PR!

**Comment by LinusU** [comment]
Published as `2.17.1`, thanks for the quick PR!

**Pull request merged**
