### PR TITLE
Fix #123 by checking number type for minimum/maximum

### LINKED ISSUE #123: `minimum` applied incorrectly for type `null`
Schema:

```json
{
	"type": ["integer", "null"],
	"minimum": 1
}
```

Intended valid JSON inputs:

```json
1
```

```json
null
```

Intended invalid JSON inputs:

```json
0
```

- Expected: `null` is considered valid
- Actual: `null` is considered invalid

Effectively, `minimum` should only be applied if the object type is `number`.

Correct behavior can be found here: http://jsonschemalint.com/draft5/

### PR DESCRIPTION
**Pull request by billinghamj**
Fixes issue in #123

### CODE REVIEW

**Comment by billinghamj** [comment]
@mafintosh Could you possibly merge this change today/tomorrow? It's causing some problems in our application

**Comment by mafintosh** [comment]
so min/max is only valid for numbers basically?

**Comment by billinghamj** [comment]
@mafintosh Correct, as per:

http://json-schema.org/latest/json-schema-validation.html#anchor13

Min/max are only applicable to numeric types

**Comment by billinghamj** [comment]
@mafintosh Could you review this please?

**Comment by billinghamj** [comment]
Perfect - thank you :)

**Pull request merged**
