### PR TITLE
Skip properties when type may be null.

### PR DESCRIPTION
**Pull request by jamesedwardcooke**

### CODE REVIEW

**Comment by jonasfj** [comment]
I would suggest adding a test case to demonstrate where this is an issue, also to ensure that it isn't reintroduced later.

**Comment by jamesedwardcooke** [comment]
Will do. Thanks!

**Comment by jonasfj** [comment]
Note, I'm not repo maintainer just a fellow user who would love to see PRs land...

**Comment by mafintosh** [comment]
Thanks. Released in 2.12.1. @jonasfj if you want to help maintain this let me know and I'll add you to the project.

**Comment by jonasfj** [comment]
> if you want to help maintain this let me know and I'll add you to the project.

@mafintosh, It depends: Do you want me landing PRs as I see fit? :) 
I would like to see this project move forward and add some features beside strict JSON schema validation. Options like `filter` properties, use `defaults`, require `additionalProperties` to specified, disallow v3-style required, etc...

Adding such options certainly increases project complexity and goes beyond the scope pure validation, however, the runtime cost will happen when you "compile" your schema to a function, not when you use your schema to validate JSON.

If you want a lot of consensus before landing PRs with features or fixes, then it's probably best that you remain gatekeeper. Otherwise, **if you trust my judgement on PRs, then yes, please add me** :)
I have considered forking, because I wanted a few things to land before I roll this out in production, but then I'm also not in a hurry to replace the other validator I'm currently.

**Pull request merged**
