### PR TITLE
Add greedy option.

### LINKED ISSUE #30: Multiple validation in the same validade(...)
Hi guys! Great module, specially on how the errors object is returned!

So, is there anyway to validate all rules at the same time, including all the rules for the same property? As I can see, is-my-json-valid is making validation in batches.

### PR DESCRIPTION
**Pull request by andreypopp**
This option is used to proceed with object validation even if it lacks all
required properties. Fixes #30.

### CODE REVIEW

**Comment by mafintosh** [comment]
whats the downside of just enabling this always?

**Comment by andreypopp** [comment]
@mafintosh I think that while validating data on server (input for API methods for example) it is sometimes more important to do things faster (bailing sooner) but with less detailed error info. That + not to break backward compatibility.

**Comment by mafintosh** [comment]
@andreypopp maybe we can just put this under the verbose option then? (that's more or less the reason it's there)

**Comment by andreypopp** [comment]
Not sure it's about verbosity as it affects validation result. I don't think that swicthing `verbose` flag should make people's tests fail/not fail. But I agree that `breakOnMissing` naming isn't very good choice.

**Comment by andreypopp** [comment]
@mafintosh updated PR as you suggested on IRC

**Comment by mafintosh** [comment]
Looks great! Released in 2.10.0

**Comment by filipedeschamps** [comment]
You guys are awesome.

**Pull request merged**
