### PR TITLE
Fix issue where the compiler would crash if a property contains a white ...

### PR DESCRIPTION
**Pull request by danieljuhl**
...space and thus is represented as data["some prop"] and additionalProps is set to false and validator is in verbose mode

### CODE REVIEW

**Comment by danieljuhl** [comment]
@mafintosh will you please take a look at this, and hopefully accept. I'm having a production issue due to this minor bug, caused by verbose mode.

**Comment by mafintosh** [comment]
its a lot safer to just use JSON.stringify actually

``` js
JSON.stringify(name+'.') + " + keys + '[' + i + ']'
```

**Comment by danieljuhl** [comment]
You're right - don't know why I didn't just do that... changed now

**Comment by mafintosh** [comment]
:+1: Releaed in 2.9.4

**Pull request merged**
