### PR TITLE
fix #59 banUnknownProperties option

### LINKED ISSUE #59: add options flag banUnknownProperties
this option should implicitly assume `additionalProperties: false` to all objects who don't explicitly defined `additionalProperties: true`.

taken from tv4 - https://github.com/geraintluff/tv4#the-banunknownproperties-flag

this helps to keep a strict validation without writing `additionalProperties: false` on all the schema levels which can be very tedious, and not necessarily desirable for production.

### PR DESCRIPTION
**Pull request by guymguym**

### CODE REVIEW

**Comment by jonasfj** [comment]
So this is a default value for `additionalProperties`?

Could we not do this by transforming the JSON schema prior to generating the JSON schema validator and get the same result?
Personally I would write my schema with `additionalProperties: false` because this also has value on documentation.

**Comment by guymguym** [comment]
@jonasfj yes - it always has a default, but the wrong default IMO :)
explicitly adding `additionalProperties: false` is ok on a small schema, but in my case I define the schema for an entire system API which is quite big, and this can quickly loose track and forget, so the idea of banning unknown properties is a way of being strict and protect the code from mistakes. I definitely prefer the schema to have a strict default and explicitly write `additionalProperties: true` when I want to live on the edge.

I considered the default as if it was appearing in the schema itself, but I didn't alter the schema object, only the validator is created differently. Were you suggesting something else?

**Comment by ebdrup** [comment]
If you want additinalProperties to be false by default. You can build a small wrapper like we did in the module schemagic.

**Comment by guymguym** [comment]
I did that of course for my system, I didn't wait for the PR to be accepted.
But for the sake of the future person trying to find this feature as I did, I preferred to contribute.

**Comment by jonasfj** [comment]
@guymguym,
Hmm... I would maybe prefer to validate that `additionalProperties` is always specified, and throw and exception if not.
This way the validator function you generate uses the JSON schema semantics from the specificiation. But you avoid cases where `additionalProperties` isn't specified explicitly, by simply refusing the create a validator function in this case.

Example:
```js
var validate = validator({
  type: 'object',
  additionalProperties: true
}, {additionalPropertiesRequired: true}); // Works

var validate = validator({
  type: 'object',
  additionalProperties: false
}, {additionalPropertiesRequired: true}); // Works

var validate = validator({
  type: 'object'
}, {additionalPropertiesRequired: true}); // throws an error

var validate = validator({
  type: 'object'
}, {additionalPropertiesRequired: false}); // works
```

This way you get a compile-time error if `additionalProperties` isn't specified. So you force schema writer to ensure that `additionalProperties` is specified.

I think this is a better way to solve the problem, because the `validate` function generated in all cases implements validation in compliance with JSON schema specification.
Also by forcing schema writers to specify `additionalProperties` explicitly, we ensure that the behaviour is reflected in schemas, which you might want to use for documentation too.

Using `banUnknownProperties` you essentially change the semantics on the JSON schema, which isn't necessary. And when reusing the schemas with another validator, documentation tools, REST client generator this change of semantics will take revenge :)

Note, I'm not maintainer of this repository, just interested. That said I like the idea of throwing compile-time errors for poorly defined schemas. Another example could be `typeRequired` validating that we always specify a `type: "..."` property.

**Comment by ebdrup** [comment]
Maybe a json-schema-lint tool (seperate from this module)

**Comment by jonasfj** [comment]
@ebdrup, a `json-schema-lint` tool sounds like a good idea...

**Comment by guymguym** [comment]
hi all. 

json-schema is a nice protocol. using `banUnknownProperties` is like a statement saying the choice of the protocol to allow additional properties by default is a bad choice. nobody forces anyone to say that. but it's a feature for those anal ppl like me who do. that's all. just like in tv4 https://github.com/geraintluff/tv4#the-banunknownproperties-flag. 

I don't get the idea to use a separate lint tool. this is my lint tool for my json's. am i to lint my lint tool now? :)

cheers :+1:

**Pull request closed without merging**
