### PR TITLE
Use `files` in package.json

### PR DESCRIPTION
**Pull request by SimenB**
This avoids installing tests and dotfiles when installing your package

### CODE REVIEW

**Comment by mafintosh** [comment]
couldn't this just be `*.js` (like tar-stream does, https://github.com/mafintosh/tar-stream/blob/master/package.json#L47-L50) to make it easier to maintain?

**Comment by SimenB** [comment]
I think being explicit is easier to maintain. If you add a new file that is needed by consumers, you add it to the array. If it's just a JS-file (maybe you decide to use Grunt/Gulp, for instance), then it's not automatically included.

As of now, this does not include `example.js`, which is a good example, IMO :smile:

**Comment by mafintosh** [comment]
we tried doing that in tar-stream and i kept forgetting to add files to pkg json. tests would still work locally so was hard to catch.

**Comment by SimenB** [comment]
What about moving the js files needed by the package (except for `index.js`) into a `lib` directory?

**Comment by mafintosh** [comment]
can you whitelist the entire lib folder then? :)

**Comment by SimenB** [comment]
Yup

**Comment by mafintosh** [comment]
i'd be fine with that :+1:

**Comment by SimenB** [comment]
@mafintosh Done :smile:

**Comment by TrySound** [comment]
@mafintosh Make new release please.

**Comment by SimenB** [comment]
@mafintosh ping

**Comment by lucleray** [comment]
@LinusU I'd love to see this PR merged.

capture d ecran 2019-01-21 a 12 12 21

**Comment by LinusU** [comment]
Hey, sorry for the late turnaround on this. I'm definitely 👍 on this.

I don't think that we should move around the files without a major break though. I've seen `require('is-my-json-valid/formats')` out in the wild, same with `/require`.


That being said, I don't think that we'll add any _new_ files in the foreseeable future, so I would be okay with listing `index.js`, `formats.js`, `require.js` and `files/` in the list, what do you think about that?

Thanks!

**Comment by SimenB** [comment]
I haven't used this module in years, feel free to tweak it or just start from scratch. It seems I've even deleted my fork 😅

**Comment by LinusU** [comment]
Sounds good, thanks for the PR and initiative!

**Pull request closed without merging**
