### PR TITLE
Output the property which is not allowed if additionalProperties is set to false

### PR DESCRIPTION
**Pull request by danieljuhl**
Up for another PR? This closes #6

### CODE REVIEW

**Comment by danieljuhl** [comment]
I decided to use the verbose mode and add the property name to the value property in the error object, eg.:

```
{
  field: 'data',
  message: 'has additional properties',
  value: 'data.foo'
}
```

**Comment by Muscula** [comment]
:+1:

**Comment by danieljuhl** [comment]
@mafintosh Any feedback to this one?

**Comment by mafintosh** [comment]
@danieljuhl I was out camping in the weekend! Looks great. Released in 2.8.0

**Comment by danieljuhl** [comment]
@mafintosh No worries - take your time :)

**Pull request merged**
