### PR TITLE
verbose mode add `type`

### PR DESCRIPTION
**Pull request by nswbmw**

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
I feel perhaps `expected` / `actual` might be better - to put it in line with the `assert` core package - do think this might be useful

**Comment by nswbmw** [comment]
I think about it, and maybe it's semantic:

```
{field: 'data.hello', message: 'is the wrong type', actual: 100, expected: 'string'}
```

But for compatibility, only add a `type` field finally:

```
{field: 'data.hello', message: 'is the wrong type', value: 100, type: 'string'}
```

**Comment by yoshuawuyts** [comment]
Yeah, that's fair +0 on which one to choose. Patch LGTM

**Comment by mafintosh** [comment]
2.13.0

**Comment by yoshuawuyts** [comment]
@nswbmw thanks for the patch! :sparkles:

**Pull request merged**
